[package]
name = "hat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "server"
path = "./src/server.rs"

[dependencies]
getrandom = "0.2.10"
rustls = "0.21.8"
